version: '3.3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./services/nginx/app_domain.com.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
  app:
    build:
      context: services/app
      dockerfile: Dockerfile.development
    command: sh -c "yarn start"
    ports:
      # https://docs.docker.com/compose/compose-file/#ports
      - "3000:3000"
    volumes:
  # https://docs.docker.com/compose/compose-file/#volumes
      - "~/.bash_history:/.bash_history"
      - "./services/app:/usr/src/app:cached"
      - "/tmp:/tmp:delegated"